name: Cypress Tests with Install Job and UI Chrome Job x 5

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: true
    #   matrix:
    #     containers: [1, 2, 3, 4, 5]
    steps:
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mongo:latest
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cypress install
        start: npm run watch
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 30
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_INCLUDE_TAGS: 'my-feature1,my-feature2'