name: Cypress smoke tests

on: 
  push:
    branches: [master]
  # schedule:
  # - cron: "5 14 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        containers: [1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          start: yarn run watch
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_INCLUDE_TAGS: smoke,regression npx cypress run